### PR TITLE
Analyze each leaflet separately

### PR DESCRIPTION
**Pull request by uppittu11**
Since tails in different leaflets may orient themselves at slightly differing angles, we should calculate the S2 and tilt angle for each leaflet separately. This PR will use the COMs of each tail to determine the center of each leaflet and then calculate the S2 and tilt for each leaflet found.

### CODE REVIEW

**Comment by uppittu11** [comment]
One issue is that we're not guaranteed to have the same number of lipids in each leaflet. This makes the resulting tilt angle array (which returns the tilt angle for each lipid) a jagged array, which isn't very convenient to manipulate. 

A next step would be to flesh out the `analysis.data` module to handle the data manipulation (like calculating averages/block averages, standard deviations, etc. of properties for each leaflet) so that the user doesn't have to deal with the `results.p` data structure directly.

**Comment by uppittu11** [comment]
Here is an example of how you would load up the S2 and tilt data and get the average values per leaflet:
https://gist.github.com/uppittu11/70e9d645d658befa2a8ff3ebfc8bafba

**Comment by chrisiacovella** [comment]
Do we want to have the code perform a layer-by-layer analysis automatically by default?  I don't see any reason to have that not be the default behavior.  The code also easily output a system wide average analysis at the same time.

**Comment by uppittu11** [comment]
Yep, layer-by-layer is the default. You can calculate averages for each layer and overall averages since all of the data is in the `results.p` data structure. An example of that is in the gist I posted above.

**Pull request merged**
